version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: gunicorn --bind 0.0.0.0:8000 HemoHub.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=HemoHub.settings
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A HemoHub.celery_app worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery-beat
    command: celery -A HemoHub.celery_app beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:latest
    container_name: redis

# No database service needed for SQLite



