# Dockerfile.web

FROM python:3.11-slim

WORKDIR /code

# Install dependencies
COPY requirements.txt /code/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the rest of the application code
COPY . /code/

# Collect static files
RUN python manage.py collectstatic --noinput

# Run the application using Gunicorn
CMD ["gunicorn", "HemoHub.wsgi:application", "--bind", "0.0.0.0:8000"]





