# Generated by Django 5.0.6 on 2024-06-27 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_Name', models.CharField(max_length=500)),
                ('Blood_Type', models.CharField(max_length=200)),
                ('Component', models.CharField(max_length=500)),
                ('Quantity', models.IntegerField()),
                ('Expiry_Date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('person_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HemoHubApp.persondata')),
            ],
        ),
    ]
